name: test

on:
  push:

jobs:
  matrix_1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        n: [1, 2, 3]
    outputs:
      output_n: ${{ steps.echo.outputs.n }}
    steps:
      - name: Echo n
        id: echo
        run: echo "n=${{ matrix.n }} >> $GITHUB_OUTPUT"

  matrix_2:
    runs-on: ubuntu-latest
    needs: matrix_1
    strategy:
      matrix:
        n: [4, 5, 6]
    steps:
      - name: Echo n
        run: echo ${{ needs.matrix_1 }}
