name: test

on:
  push:

jobs:
  matrix_1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        n: [1, 2, 3]
    steps:
      - name: Echo n
        run: echo ${{ matrix.n }}

  matrix_2:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        n: [4, 5, 6]
    steps:
      - name: Echo n
        run: echo ${{ matrix.n }}
